### ISSUE TITLE
Whenever I reopen VS Code, the Checkmarx plugin requires me to login again in order to run a scan.  Error:  "Access token expired. Please login again."

### ISSUE THREAD

**Issue by mendhak** [checkmarx-ltd/cxvscode#13]
Whenever I reopen VS Code, the Checkmarx plugin requires me to login again in order to run a scan.  How can I get the plugin to remember my login so that I don't have to keep logging in whenever I want to run a scan?  Is there a way to tell if there's something wrong on my end?  My colleagues have the same problem, and we need to re-login each time. 

### Steps
[Follow the VS Code setup instructions](https://checkmarx.atlassian.net/wiki/spaces/SD/pages/1759216424/Setting+Up+the+Visual+Studio+Code+Extension+Plugin).  
Install the Checkmarx plugin and set up a CxPortal server. 
Click Padlock icon, login with Credentials.   
Click Book icon, bind your project.    
Run a scan if you want.  This scan works. 

![image](https://user-images.githubusercontent.com/746276/100369421-c64aff80-2ffc-11eb-8733-0dd1018e7d40.png)

Close VS Code.  

Open VS Code. 

Try running a scan again. This error appears:

> "Access token expired. Please login again."

Checkmarx console shows:

> Error: Access token expired. Please login.
Sending GET request to https://checkmarx.internal/CxRestAPI/projects
GET request failed to https://checkmarx.internal/CxRestAPI/projects
Error: unable to get local issuer certificate
Sending GET request to https://checkmarx.internal/CxRestAPI/projects
GET request failed to https://checkmarx.internal/CxRestAPI/projects
Error: unable to get local issuer certificate
Error: Access token expired. Please login.

![image](https://user-images.githubusercontent.com/746276/100368015-f5607180-2ffa-11eb-930d-6fc51ebf10fc.png)

Now in CX Portal, click the padlock and login to Checkmarx portal again.  Run a scan.  It works.  

**Note**: it doesn't matter if I set up the plugin via settings.json directly or via the UI steps.  We're facing the same problem each time we reopen VS Code.

**Comment by jbrotsos** [comment]
This has been fixed in the latest release.

Let me know if you have any other questions.

@jbrotsos
