### ISSUE TITLE
Update Readme with language support

### ISSUE THREAD

**Issue by Romiko** [checkmarx-ltd/cxvscode#39]
Please provide a list of languages supported e.g. C#, Node.JS, Python etc in the README.md file.
Thanks

**Comment by jbrotsos** [comment]
Hey @Romiko ,

The list of supported languages can be found here:

https://checkmarx.atlassian.net/wiki/spaces/SAST/pages/3206493690/Supported+Code+Languages+and+Frameworks

Let me know if you have any other questions.

@jbrotsos
